-- Guitar Slash - contas, configuracoes e placar
--
-- Rode no SQL Editor do Supabase (ou via CLI). E idempotente: pode rodar de
-- novo sem estragar nada.
--
-- REGRA DE OURO DESTE ARQUIVO: toda tabela tem RLS LIGADO e politicas
-- explicitas. Sem isso, a anon key (que vai embutida no frontend, e portanto e
-- publica) daria acesso de leitura e escrita a tudo.

-- ============================================================ perfis

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 24),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.profiles is
  'Nome publico do jogador. Fica separado de auth.users porque o leaderboard
   precisa ler o nome de todos, e auth.users nunca deve ser exposta.';

alter table public.profiles enable row level security;

-- Leitura publica: o leaderboard mostra o nome de quem pontuou.
drop policy if exists "perfis sao publicos" on public.profiles;
create policy "perfis sao publicos"
  on public.profiles for select
  using (true);

drop policy if exists "cria o proprio perfil" on public.profiles;
create policy "cria o proprio perfil"
  on public.profiles for insert
  with check (auth.uid() = id);

drop policy if exists "edita o proprio perfil" on public.profiles;
create policy "edita o proprio perfil"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- ================================================= configuracoes na nuvem

create table if not exists public.player_settings (
  user_id uuid primary key references auth.users (id) on delete cascade,
  -- O formato fica no cliente (settings/types.ts) e evolui com `version`.
  -- Guardar como jsonb evita migracao de banco a cada campo novo de opcao.
  settings jsonb not null,
  updated_at timestamptz not null default now()
);

alter table public.player_settings enable row level security;

-- Configuracao e privada: sem leitura publica, diferente do perfil.
drop policy if exists "le as proprias configuracoes" on public.player_settings;
create policy "le as proprias configuracoes"
  on public.player_settings for select
  using (auth.uid() = user_id);

drop policy if exists "grava as proprias configuracoes" on public.player_settings;
create policy "grava as proprias configuracoes"
  on public.player_settings for insert
  with check (auth.uid() = user_id);

drop policy if exists "atualiza as proprias configuracoes" on public.player_settings;
create policy "atualiza as proprias configuracoes"
  on public.player_settings for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- ============================================================ placares

create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  song_id text not null,
  instrument text not null,
  difficulty text not null,
  score integer not null check (score >= 0),
  accuracy real not null check (accuracy >= 0 and accuracy <= 1),
  max_combo integer not null default 0 check (max_combo >= 0),
  notes_hit integer not null default 0 check (notes_hit >= 0),
  notes_missed integer not null default 0 check (notes_missed >= 0),
  stars smallint not null default 0 check (stars between 0 and 5),
  created_at timestamptz not null default now(),

  constraint instrumento_valido
    check (instrument in ('guitar', 'guitar_coop', 'rhythm', 'bass', 'drums')),
  constraint dificuldade_valida
    check (difficulty in ('easy', 'medium', 'hard', 'expert'))
);

comment on table public.scores is
  'Uma linha por partida terminada. Mantem o historico em vez de so o recorde,
   porque o recorde e derivavel e o historico nao.';

-- O leaderboard le por musica/instrumento/dificuldade ordenando por score.
create index if not exists scores_ranking_idx
  on public.scores (song_id, instrument, difficulty, score desc);

-- "Meus placares" le por usuario, mais recentes primeiro.
create index if not exists scores_usuario_idx
  on public.scores (user_id, created_at desc);

alter table public.scores enable row level security;

-- Leitura publica: e um leaderboard.
drop policy if exists "placares sao publicos" on public.scores;
create policy "placares sao publicos"
  on public.scores for select
  using (true);

-- Insercao apenas em nome proprio. NAO ha politica de update nem de delete:
-- placar enviado nao se reescreve, o que fecha a porta para "corrigir" um
-- recorde depois.
drop policy if exists "envia o proprio placar" on public.scores;
create policy "envia o proprio placar"
  on public.scores for insert
  with check (auth.uid() = user_id);

-- ================================================== leaderboard (view)

-- Melhor placar de cada jogador por musica/instrumento/dificuldade, com o nome
-- ja resolvido. `security_invoker` faz a view respeitar a RLS de quem consulta,
-- em vez de rodar com os poderes do dono.
drop view if exists public.leaderboard;
create view public.leaderboard
with (security_invoker = true)
as
select distinct on (s.song_id, s.instrument, s.difficulty, s.user_id)
  s.song_id,
  s.instrument,
  s.difficulty,
  s.user_id,
  p.display_name,
  s.score,
  s.accuracy,
  s.max_combo,
  s.stars,
  s.created_at
from public.scores s
join public.profiles p on p.id = s.user_id
order by
  s.song_id, s.instrument, s.difficulty, s.user_id, s.score desc;

comment on view public.leaderboard is
  'Um registro por jogador: o melhor placar dele naquela combinacao.';

-- ====================================== perfil automatico ao cadastrar

-- Sem isto, o jogador cadastra e fica sem perfil ate a primeira gravacao - e o
-- leaderboard (que faz join com profiles) o esconderia.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    -- Nome vindo do cadastro; se nao houver, a parte local do e-mail.
    coalesce(
      nullif(trim(new.raw_user_meta_data ->> 'display_name'), ''),
      split_part(new.email, '@', 1),
      'Player'
    )
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ============================================ updated_at automatico

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_touch on public.profiles;
create trigger profiles_touch
  before update on public.profiles
  for each row execute function public.touch_updated_at();

drop trigger if exists player_settings_touch on public.player_settings;
create trigger player_settings_touch
  before update on public.player_settings
  for each row execute function public.touch_updated_at();
